version: "3.9"
services:
  frontend:
    build: ./vunerabilidade-front
    ports:
      - "8081:80" 
    depends_on:
      - backend

  backend:
    build: ./projeto-app-notaFlow
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/db_notaflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=senha
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: db_notaflow
      MARIADB_ROOT_PASSWORD: senha
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dbdata: